image: node:12-buster

pipelines:
  default:
    - parallel:
      - step:
          name: Lint
          caches:
            - node
          script:
            - npm install
            - npm run lint
      - step:
          name: Test
          caches:
            - node
          script:
            - npm install
            - npm run test
  branches:
    master:
      - parallel:
        - step:
            name: Lint
            caches:
              - node
            script:
              - npm install
              - npm run lint
        - step:
            name: Test
            caches:
              - node
            script:
              - npm install
              - npm run test
      - step:
          name: Release
          caches:
            - node
          script:
            - npm install
            - npm run docs
            - npm run semantic-release
